modLoader="javafml"
loaderVersion="[47,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="chef"
version="1.1.0"
displayName="Chef"
displayURL="https://github.com/BetaT81717/Chef"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="SlavicCapybara"
description="Adds more food"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.chef]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration